# Generated by Django 3.2.12 on 2022-04-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor_info',
            name='date_created',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
