# Generated by Django 3.2.12 on 2022-05-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_sensor_info_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122, null=True)),
                ('email', models.CharField(max_length=122, null=True)),
            ],
        ),
    ]
