# Generated by Django 3.2.12 on 2022-05-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_request_access'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request_access',
            new_name='request_access_model',
        ),
    ]
